### PR TITLE
WIP: Set the default timezone to NULL on dbConnect

### PR DESCRIPTION
**Pull request by cswingle**
This resolves Issue #229 (when built with DBI >= 1.0.0.9003)

### CODE REVIEW

**Comment by trafficonese** [comment]
I think you missed to update the documentation.
Thats why travis is nagging.

**Comment by cswingle** [comment]
@trafficonese Thanks. You're right. I updated the help page to match the internal documentation.

**Comment by cswingle** [comment]
Not sure what to do about the Travis CI build fail. It looks to me like maybe it's this: `A complete check needs the 'checkbashisms' script`, but I haven't a clue how to fix that. When I run `devtools::check(error_on = "warning")` on my system I get a clean check (Linux, AMD64, R 3.6.1, DBI and friends from github).

**Comment by trafficonese** [comment]
I was wondering about that aswell, then I saw the commit https://github.com/r-dbi/RPostgres/pull/230/commits/27c079860c25b7c52ff75ce01a239c72a683da5a of #230 which apparently fixed the `checkbashisms` problem.

**Comment by cswingle** [comment]
Thanks. I just saw that too and did the same thing with 5c9a349. Fingers crossed.

**Comment by cswingle** [comment]
I've been playing with this pull request, and while it does solve the issue with #229 it breaks normal retrieval of `timestamp with time zone` data from Postgres. With this patch in place, it doesn't seem possible to retrieve the correct timestamp value regardless of what value you use in the `timestamp` argument to `dbConnect`. Back to the drawing board on #229, I guess.

**Comment by krlmlr** [comment]
Thanks. Let me keep it open as a WIP to see what hasn't worked.

**Comment by krlmlr** [comment]
Thanks again. This should be now fixed with #276. I suspect we need to keep the default for `timezone` to `"UTC"`.

**Pull request closed without merging**
