### PR TITLE
Add LISTEN/NOTIFY support

### PR DESCRIPTION
**Pull request by lentinj**
The following adds ``postgresWaitForNotify``, which returns the next available message on the channels that your connection is ``LISTEN``ing to. See the documentation for a brief example, I've got a fuller example using this to orchestrate multiple R workers running a function, which I'll publish as a blog post if this gets accepted. If you're interested I could throw the code from this somewhere now.

As this is Postgres-specific functionality, we don't add this to DBI, rather expose it directly from RPostgres (this roughly matches what both Perl and Ruby's DBI do).

Some other links:-

* [Postgres documentation on LISTEN](https://www.postgresql.org/docs/current/sql-notify.html)
* [libpq C example of receiving notifications](https://www.postgresql.org/docs/current/libpq-example.html#LIBPQ-EXAMPLE-2)
* [Equivalent interface in Ruby](https://gist.github.com/chsh/9c9f5702919c83023f83)
* [Equivalent interface in Python](http://initd.org/psycopg/docs/advanced.html#asynchronous-notifications)

### CODE REVIEW

**Comment by krlmlr** [comment]
I received a winbuilder e-mail with results: https://win-builder.r-project.org/bVv201J1GFB9/ . You can direct the check results to your account by updating maintainer e-mail in `DESCRIPTION` before sending, e.g.:

```r
devtools::check_win_devel(email = "lentinj@mail.xyz")
```

**Comment by lentinj** [comment]
> I received a winbuilder e-mail with results

Sorry! I thought I stopped the upload in time. Thanks for forwarding.

**Comment by lentinj** [comment]
@krlmlr I think I'm done tinkering with this (and spamming you with test reports) now. Let me know if you think it needs anything else.

As for a vignette, I'll play with this once I've battle tested my code a bit. Would you prefer this in the DBI repo (where the other vignettes are), or here?

**Comment by krlmlr** [comment]
Thanks. If you still want to contribute a vignette, this repo (and this PR) would be a great place.

**Comment by krlmlr** [comment]
Thanks for your work on this!

**Comment by lentinj** [comment]
Thanks also for adding ``eval = RPostgres::postgresHasDefault()``, I was struggling to work out how you would do it. Now I know :)

**Pull request merged**
